module.exports = {
  MONGOURI: process.env.MONGOURI,
  JWT_SECRET: process.env.JWT_SECRET,
  CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
  CLOUDINARY_API: process.env.CLOUDINARY_API,
  CLOUDNIARY_SECRET: process.env.CLOUDNIARY_SECRET,
  SENDGRID_API: process.env.SENDGRID_API,
  EMAIL_PASS: process.env.EMAIL_PASS,
  GOOGLE_MAP_API: process.env.GOOGLE_MAP_API,
};
